/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Apr 19, 2012, 4:41:39 PM
 */

package project1_ema_tni.gui;

import java.awt.Dimension;

/**
 *
 * @author andre
 */
public class MainWindow extends javax.swing.JFrame {
    private static Dimension defaultWindowDim = new Dimension(600, 50);

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
    }


    /**
     * @param args the command line arguments
     */
    public static void mainDisabled(String[] args)
    {
        MainWindow mainWindow = new MainWindow();
        mainWindow.setMinimumSize(defaultWindowDim);
        mainWindow.setMaximumSize(defaultWindowDim);
        mainWindow.setPreferredSize(defaultWindowDim);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
